/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.agenda.gui;

/**
 *
 * @author LENOVO
 */
public class AgendaGui extends javax.swing.JFrame {

    /**
     * Creates new form AgendaGui
     */
    public AgendaGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bandeja = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        loginFondo2 = new javax.swing.JPanel();
        loginFondo3 = new javax.swing.JPanel();
        loginBtn1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        loginFondo6 = new javax.swing.JPanel();
        loginFondo7 = new javax.swing.JPanel();
        loginBtn2 = new javax.swing.JLabel();
        loginFondo8 = new javax.swing.JPanel();
        loginFondo9 = new javax.swing.JPanel();
        loginBtn4 = new javax.swing.JLabel();
        loginFondo10 = new javax.swing.JPanel();
        loginFondo11 = new javax.swing.JPanel();
        loginBtn5 = new javax.swing.JLabel();
        loginFondo12 = new javax.swing.JPanel();
        loginFondo14 = new javax.swing.JPanel();
        loginBtn3 = new javax.swing.JLabel();
        loginFondo4 = new javax.swing.JPanel();
        loginFondo5 = new javax.swing.JPanel();
        loginBtn7 = new javax.swing.JLabel();
        loginFondo = new javax.swing.JPanel();
        loginFondo1 = new javax.swing.JPanel();
        loginFondo15 = new javax.swing.JPanel();
        loginFondo16 = new javax.swing.JPanel();
        loginBtn = new javax.swing.JLabel();
        loginFondo13 = new javax.swing.JPanel();
        loginBtn6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        loginFondo17 = new javax.swing.JPanel();
        loginFondo18 = new javax.swing.JPanel();
        loginFondo19 = new javax.swing.JPanel();
        loginFondo20 = new javax.swing.JPanel();
        loginBtn8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONTACTOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 280, 77));

        bandeja.setBackground(new java.awt.Color(153, 153, 255));
        jScrollPane1.setViewportView(bandeja);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 450, 420));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFondo2.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo2.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo2.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo2MouseDragged(evt);
            }
        });
        loginFondo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo2FocusGained(evt);
            }
        });
        loginFondo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo2MouseReleased(evt);
            }
        });
        loginFondo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFondo3.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo3.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo3.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo3MouseDragged(evt);
            }
        });
        loginFondo3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo3FocusGained(evt);
            }
        });
        loginFondo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo3MouseReleased(evt);
            }
        });
        loginFondo3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        loginFondo2.add(loginFondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 60, 60));

        loginBtn1.setBackground(new java.awt.Color(255, 102, 204));
        loginBtn1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        loginBtn1.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn1.setText("+");
        loginBtn1.setToolTipText("");
        loginBtn1.setPreferredSize(new java.awt.Dimension(50, 50));
        loginBtn1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginBtn1FocusGained(evt);
            }
        });
        loginBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtn1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtn1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtn1MouseReleased(evt);
            }
        });
        loginFondo2.add(loginBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel2.add(loginFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 60, 60));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFondo6.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo6.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo6.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo6MouseDragged(evt);
            }
        });
        loginFondo6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo6FocusGained(evt);
            }
        });
        loginFondo6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo6MouseReleased(evt);
            }
        });
        loginFondo6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFondo7.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo7.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo7.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo7MouseDragged(evt);
            }
        });
        loginFondo7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo7FocusGained(evt);
            }
        });
        loginFondo7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo7MouseReleased(evt);
            }
        });
        loginFondo7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        loginFondo6.add(loginFondo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 60, 60));

        loginBtn2.setBackground(new java.awt.Color(255, 102, 204));
        loginBtn2.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        loginBtn2.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn2.setText("+");
        loginBtn2.setToolTipText("");
        loginBtn2.setPreferredSize(new java.awt.Dimension(50, 50));
        loginBtn2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginBtn2FocusGained(evt);
            }
        });
        loginBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtn2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtn2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtn2MouseReleased(evt);
            }
        });
        loginFondo6.add(loginBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel3.add(loginFondo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 60, 60));

        loginFondo8.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo8.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo8.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo8MouseDragged(evt);
            }
        });
        loginFondo8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo8FocusGained(evt);
            }
        });
        loginFondo8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo8MouseReleased(evt);
            }
        });
        loginFondo8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFondo9.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo9.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo9.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo9MouseDragged(evt);
            }
        });
        loginFondo9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo9FocusGained(evt);
            }
        });
        loginFondo9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo9MouseReleased(evt);
            }
        });
        loginFondo9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        loginFondo8.add(loginFondo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 60, 60));

        loginBtn4.setBackground(new java.awt.Color(255, 102, 204));
        loginBtn4.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        loginBtn4.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn4.setText("-");
        loginBtn4.setToolTipText("");
        loginBtn4.setPreferredSize(new java.awt.Dimension(50, 50));
        loginBtn4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginBtn4FocusGained(evt);
            }
        });
        loginBtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtn4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtn4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtn4MouseReleased(evt);
            }
        });
        loginFondo8.add(loginBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel3.add(loginFondo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, 60));

        loginFondo10.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo10.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo10.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo10MouseDragged(evt);
            }
        });
        loginFondo10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo10FocusGained(evt);
            }
        });
        loginFondo10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo10MouseReleased(evt);
            }
        });
        loginFondo10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFondo11.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo11.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo11.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo11MouseDragged(evt);
            }
        });
        loginFondo11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo11FocusGained(evt);
            }
        });
        loginFondo11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo11MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo11MouseReleased(evt);
            }
        });
        loginFondo11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        loginFondo10.add(loginFondo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 60, 60));

        loginBtn5.setBackground(new java.awt.Color(255, 102, 204));
        loginBtn5.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        loginBtn5.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn5.setText("🔍");
        loginBtn5.setToolTipText("");
        loginBtn5.setPreferredSize(new java.awt.Dimension(50, 50));
        loginBtn5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginBtn5FocusGained(evt);
            }
        });
        loginBtn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtn5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtn5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtn5MouseReleased(evt);
            }
        });
        loginFondo10.add(loginBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel3.add(loginFondo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 260, 60));

        loginFondo12.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo12.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo12.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo12MouseDragged(evt);
            }
        });
        loginFondo12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo12FocusGained(evt);
            }
        });
        loginFondo12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo12MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo12MouseReleased(evt);
            }
        });
        loginFondo12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFondo14.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo14.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo14.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo14MouseDragged(evt);
            }
        });
        loginFondo14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo14FocusGained(evt);
            }
        });
        loginFondo14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo14MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo14MouseReleased(evt);
            }
        });
        loginFondo14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        loginFondo12.add(loginFondo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 60, 60));

        loginBtn3.setBackground(new java.awt.Color(255, 102, 204));
        loginBtn3.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        loginBtn3.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn3.setText("-");
        loginBtn3.setToolTipText("");
        loginBtn3.setPreferredSize(new java.awt.Dimension(50, 50));
        loginBtn3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginBtn3FocusGained(evt);
            }
        });
        loginBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtn3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtn3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtn3MouseReleased(evt);
            }
        });
        loginFondo12.add(loginBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel2.add(loginFondo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 60, 60));

        loginFondo4.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo4.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo4.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo4MouseDragged(evt);
            }
        });
        loginFondo4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo4FocusGained(evt);
            }
        });
        loginFondo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo4MouseReleased(evt);
            }
        });
        loginFondo4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFondo5.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo5.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo5.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo5MouseDragged(evt);
            }
        });
        loginFondo5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo5FocusGained(evt);
            }
        });
        loginFondo5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo5MouseReleased(evt);
            }
        });
        loginFondo5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        loginFondo4.add(loginFondo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 60, 60));

        loginBtn7.setBackground(new java.awt.Color(255, 102, 204));
        loginBtn7.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        loginBtn7.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn7.setText("🔍");
        loginBtn7.setToolTipText("");
        loginBtn7.setPreferredSize(new java.awt.Dimension(50, 50));
        loginBtn7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginBtn7FocusGained(evt);
            }
        });
        loginBtn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtn7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtn7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtn7MouseReleased(evt);
            }
        });
        loginFondo4.add(loginBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel2.add(loginFondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, 60));

        loginFondo.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondoMouseDragged(evt);
            }
        });
        loginFondo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondoFocusGained(evt);
            }
        });
        loginFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondoMouseReleased(evt);
            }
        });
        loginFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFondo1.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo1.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo1.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo1MouseDragged(evt);
            }
        });
        loginFondo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo1FocusGained(evt);
            }
        });
        loginFondo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo1MouseReleased(evt);
            }
        });
        loginFondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        loginFondo.add(loginFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 60, 60));

        loginFondo15.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo15.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo15.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo15MouseDragged(evt);
            }
        });
        loginFondo15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo15FocusGained(evt);
            }
        });
        loginFondo15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo15MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo15MouseReleased(evt);
            }
        });
        loginFondo15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFondo16.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo16.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo16.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo16.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo16MouseDragged(evt);
            }
        });
        loginFondo16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo16FocusGained(evt);
            }
        });
        loginFondo16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo16MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo16MouseReleased(evt);
            }
        });
        loginFondo16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        loginFondo15.add(loginFondo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 60, 60));

        loginFondo.add(loginFondo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 60, 60));

        loginBtn.setBackground(new java.awt.Color(255, 102, 204));
        loginBtn.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn.setText("✍");
        loginBtn.setToolTipText("");
        loginBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        loginBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginBtnFocusGained(evt);
            }
        });
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtnMouseReleased(evt);
            }
        });
        loginFondo.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel2.add(loginFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 60, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 330, 60));

        loginFondo13.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo13.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo13.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo13MouseDragged(evt);
            }
        });
        loginFondo13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo13FocusGained(evt);
            }
        });
        loginFondo13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo13MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo13MouseReleased(evt);
            }
        });
        loginFondo13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBtn6.setBackground(new java.awt.Color(255, 102, 204));
        loginBtn6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        loginBtn6.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn6.setText("NUEVO MENSAJE");
        loginBtn6.setToolTipText("");
        loginBtn6.setPreferredSize(new java.awt.Dimension(50, 50));
        loginBtn6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginBtn6FocusGained(evt);
            }
        });
        loginBtn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtn6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtn6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtn6MouseReleased(evt);
            }
        });
        loginFondo13.add(loginBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 60));

        jPanel1.add(loginFondo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 270, 60));

        jList2.setBackground(new java.awt.Color(153, 153, 255));
        jScrollPane3.setViewportView(jList2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 270, 420));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BANDEJA DE ENTRADA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 500, 77));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 40, 410));

        loginFondo17.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo17.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo17.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo17.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo17MouseDragged(evt);
            }
        });
        loginFondo17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo17FocusGained(evt);
            }
        });
        loginFondo17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo17MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo17MouseReleased(evt);
            }
        });
        loginFondo17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFondo18.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo18.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo18.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo18.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo18MouseDragged(evt);
            }
        });
        loginFondo18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo18FocusGained(evt);
            }
        });
        loginFondo18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo18MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo18MouseReleased(evt);
            }
        });
        loginFondo18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        loginFondo17.add(loginFondo18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 60, 60));

        loginFondo19.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo19.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo19.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo19.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo19MouseDragged(evt);
            }
        });
        loginFondo19.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo19FocusGained(evt);
            }
        });
        loginFondo19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo19MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo19MouseReleased(evt);
            }
        });
        loginFondo19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFondo20.setBackground(new java.awt.Color(255, 102, 204));
        loginFondo20.setMinimumSize(new java.awt.Dimension(50, 50));
        loginFondo20.setPreferredSize(new java.awt.Dimension(50, 50));
        loginFondo20.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginFondo20MouseDragged(evt);
            }
        });
        loginFondo20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFondo20FocusGained(evt);
            }
        });
        loginFondo20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginFondo20MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginFondo20MouseReleased(evt);
            }
        });
        loginFondo20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        loginFondo19.add(loginFondo20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 60, 60));

        loginFondo17.add(loginFondo19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 60, 60));

        loginBtn8.setBackground(new java.awt.Color(255, 102, 204));
        loginBtn8.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        loginBtn8.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn8.setText("🔄️");
        loginBtn8.setToolTipText("");
        loginBtn8.setPreferredSize(new java.awt.Dimension(50, 50));
        loginBtn8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginBtn8FocusGained(evt);
            }
        });
        loginBtn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtn8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtn8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtn8MouseReleased(evt);
            }
        });
        loginFondo17.add(loginBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel1.add(loginFondo17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginBtnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnFocusGained

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnMouseClicked

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnMouseExited

    private void loginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMousePressed
       // loginFondo.setBackground(new Color(255,153,204));  // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnMousePressed

    private void loginBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseReleased
        //loginFondo.setBackground(new Color(255, 102, 204));         // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnMouseReleased

    private void loginFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondoMouseDragged

    private void loginFondoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondoFocusGained

    private void loginFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondoMousePressed

    private void loginFondoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondoMouseReleased

    private void loginFondo1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo1MouseDragged

    private void loginFondo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo1FocusGained

    private void loginFondo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo1MousePressed

    private void loginFondo1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo1MouseReleased

    private void loginFondo3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo3MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo3MouseDragged

    private void loginFondo3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo3FocusGained

    private void loginFondo3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo3MousePressed

    private void loginFondo3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo3MouseReleased

    private void loginFondo2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo2MouseDragged

    private void loginFondo2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo2FocusGained

    private void loginFondo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo2MousePressed

    private void loginFondo2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo2MouseReleased

    private void loginBtn1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginBtn1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1FocusGained

    private void loginBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1MouseClicked

    private void loginBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1MouseExited

    private void loginBtn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1MousePressed

    private void loginBtn1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1MouseReleased

    private void loginFondo5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo5MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo5MouseDragged

    private void loginFondo5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo5FocusGained

    private void loginFondo5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo5MousePressed

    private void loginFondo5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo5MouseReleased

    private void loginBtn3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginBtn3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn3FocusGained

    private void loginBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn3MouseClicked

    private void loginBtn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn3MouseExited

    private void loginBtn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn3MousePressed

    private void loginBtn3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn3MouseReleased

    private void loginFondo4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo4MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo4MouseDragged

    private void loginFondo4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo4FocusGained

    private void loginFondo4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo4MousePressed

    private void loginFondo4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo4MouseReleased

    private void loginFondo7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo7MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo7MouseDragged

    private void loginFondo7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo7FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo7FocusGained

    private void loginFondo7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo7MousePressed

    private void loginFondo7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo7MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo7MouseReleased

    private void loginBtn2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginBtn2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn2FocusGained

    private void loginBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn2MouseClicked

    private void loginBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn2MouseExited

    private void loginBtn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn2MousePressed

    private void loginBtn2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn2MouseReleased

    private void loginFondo6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo6MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo6MouseDragged

    private void loginFondo6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo6FocusGained

    private void loginFondo6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo6MousePressed

    private void loginFondo6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo6MouseReleased

    private void loginFondo9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo9MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo9MouseDragged

    private void loginFondo9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo9FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo9FocusGained

    private void loginFondo9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo9MousePressed

    private void loginFondo9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo9MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo9MouseReleased

    private void loginBtn4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginBtn4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn4FocusGained

    private void loginBtn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn4MouseClicked

    private void loginBtn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn4MouseExited

    private void loginBtn4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn4MousePressed

    private void loginBtn4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn4MouseReleased

    private void loginFondo8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo8MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo8MouseDragged

    private void loginFondo8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo8FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo8FocusGained

    private void loginFondo8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo8MousePressed

    private void loginFondo8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo8MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo8MouseReleased

    private void loginFondo11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo11MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo11MouseDragged

    private void loginFondo11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo11FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo11FocusGained

    private void loginFondo11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo11MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo11MousePressed

    private void loginFondo11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo11MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo11MouseReleased

    private void loginBtn5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginBtn5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn5FocusGained

    private void loginBtn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn5MouseClicked

    private void loginBtn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn5MouseExited

    private void loginBtn5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn5MousePressed

    private void loginBtn5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn5MouseReleased

    private void loginFondo10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo10MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo10MouseDragged

    private void loginFondo10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo10FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo10FocusGained

    private void loginFondo10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo10MousePressed

    private void loginFondo10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo10MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo10MouseReleased

    private void loginFondo13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo13MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo13MouseDragged

    private void loginFondo13FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo13FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo13FocusGained

    private void loginFondo13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo13MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo13MousePressed

    private void loginFondo13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo13MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo13MouseReleased

    private void loginBtn6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn6MouseReleased

    private void loginBtn6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn6MousePressed

    private void loginBtn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn6MouseExited

    private void loginBtn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn6MouseClicked

    private void loginBtn6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginBtn6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn6FocusGained

    private void loginFondo14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo14MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo14MouseDragged

    private void loginFondo14FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo14FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo14FocusGained

    private void loginFondo14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo14MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo14MousePressed

    private void loginFondo14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo14MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo14MouseReleased

    private void loginBtn7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginBtn7FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn7FocusGained

    private void loginBtn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn7MouseClicked

    private void loginBtn7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn7MouseExited

    private void loginBtn7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn7MousePressed

    private void loginBtn7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn7MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn7MouseReleased

    private void loginFondo12MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo12MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo12MouseDragged

    private void loginFondo12FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo12FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo12FocusGained

    private void loginFondo12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo12MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo12MousePressed

    private void loginFondo12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo12MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo12MouseReleased

    private void loginFondo16MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo16MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo16MouseDragged

    private void loginFondo16FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo16FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo16FocusGained

    private void loginFondo16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo16MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo16MousePressed

    private void loginFondo16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo16MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo16MouseReleased

    private void loginFondo15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo15MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo15MouseDragged

    private void loginFondo15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo15FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo15FocusGained

    private void loginFondo15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo15MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo15MousePressed

    private void loginFondo15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo15MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo15MouseReleased

    private void loginFondo18MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo18MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo18MouseDragged

    private void loginFondo18FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo18FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo18FocusGained

    private void loginFondo18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo18MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo18MousePressed

    private void loginFondo18MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo18MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo18MouseReleased

    private void loginFondo20MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo20MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo20MouseDragged

    private void loginFondo20FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo20FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo20FocusGained

    private void loginFondo20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo20MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo20MousePressed

    private void loginFondo20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo20MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo20MouseReleased

    private void loginFondo19MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo19MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo19MouseDragged

    private void loginFondo19FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo19FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo19FocusGained

    private void loginFondo19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo19MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo19MousePressed

    private void loginFondo19MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo19MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo19MouseReleased

    private void loginFondo17MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo17MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo17MouseDragged

    private void loginFondo17FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFondo17FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo17FocusGained

    private void loginFondo17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo17MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo17MousePressed

    private void loginFondo17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFondo17MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFondo17MouseReleased

    private void loginBtn8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginBtn8FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn8FocusGained

    private void loginBtn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn8MouseClicked

    private void loginBtn8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn8MouseExited

    private void loginBtn8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn8MousePressed

    private void loginBtn8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn8MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn8MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> bandeja;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel loginBtn1;
    private javax.swing.JLabel loginBtn2;
    private javax.swing.JLabel loginBtn3;
    private javax.swing.JLabel loginBtn4;
    private javax.swing.JLabel loginBtn5;
    private javax.swing.JLabel loginBtn6;
    private javax.swing.JLabel loginBtn7;
    private javax.swing.JLabel loginBtn8;
    private javax.swing.JPanel loginFondo;
    private javax.swing.JPanel loginFondo1;
    private javax.swing.JPanel loginFondo10;
    private javax.swing.JPanel loginFondo11;
    private javax.swing.JPanel loginFondo12;
    private javax.swing.JPanel loginFondo13;
    private javax.swing.JPanel loginFondo14;
    private javax.swing.JPanel loginFondo15;
    private javax.swing.JPanel loginFondo16;
    private javax.swing.JPanel loginFondo17;
    private javax.swing.JPanel loginFondo18;
    private javax.swing.JPanel loginFondo19;
    private javax.swing.JPanel loginFondo2;
    private javax.swing.JPanel loginFondo20;
    private javax.swing.JPanel loginFondo3;
    private javax.swing.JPanel loginFondo4;
    private javax.swing.JPanel loginFondo5;
    private javax.swing.JPanel loginFondo6;
    private javax.swing.JPanel loginFondo7;
    private javax.swing.JPanel loginFondo8;
    private javax.swing.JPanel loginFondo9;
    // End of variables declaration//GEN-END:variables
}
