/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete.franquito;

/**
 *
 * @author LENOVO
 */
public class BuscarGui extends javax.swing.JFrame {

    /**
     * Creates new form BuscarGui
     */
    public BuscarGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        crearContactoFondo = new javax.swing.JPanel();
        crearContactoBtn = new javax.swing.JLabel();
        nombreRegistrar1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(10, 10));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BUSCAR CONTACTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 10, 400, 77));

        crearContactoFondo.setBackground(new java.awt.Color(255, 102, 204));
        crearContactoFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                crearContactoFondoMouseDragged(evt);
            }
        });
        crearContactoFondo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                crearContactoFondoFocusGained(evt);
            }
        });
        crearContactoFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearContactoFondoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                crearContactoFondoMouseReleased(evt);
            }
        });

        crearContactoBtn.setBackground(new java.awt.Color(255, 102, 204));
        crearContactoBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        crearContactoBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearContactoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearContactoBtn.setText("BUSCAR CONTACTO");
        crearContactoBtn.setToolTipText("");
        crearContactoBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                crearContactoBtnFocusGained(evt);
            }
        });
        crearContactoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearContactoBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearContactoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearContactoBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                crearContactoBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout crearContactoFondoLayout = new javax.swing.GroupLayout(crearContactoFondo);
        crearContactoFondo.setLayout(crearContactoFondoLayout);
        crearContactoFondoLayout.setHorizontalGroup(
            crearContactoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearContactoFondoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(crearContactoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        crearContactoFondoLayout.setVerticalGroup(
            crearContactoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearContactoFondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(crearContactoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(crearContactoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 180, -1));

        nombreRegistrar1.setBackground(new java.awt.Color(204, 204, 255));
        nombreRegistrar1.setForeground(new java.awt.Color(153, 153, 255));
        nombreRegistrar1.setText("Ingrese correo");
        nombreRegistrar1.setBorder(null);
        nombreRegistrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombreRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreRegistrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(nombreRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 260, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 255));
        jLabel8.setText("POR CORREO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        jSeparator4.setBackground(new java.awt.Color(255, 204, 153));
        jSeparator4.setForeground(new java.awt.Color(153, 102, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, 10));

        jList2.setBackground(new java.awt.Color(153, 153, 255));
        jScrollPane3.setViewportView(jList2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 490, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearContactoBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_crearContactoBtnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoBtnFocusGained

    private void crearContactoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoBtnMouseClicked

    private void crearContactoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoBtnMouseExited

    private void crearContactoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoBtnMousePressed
        // crearContactoFondo.setBackground(new Color(255,153,204));  // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoBtnMousePressed

    private void crearContactoBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoBtnMouseReleased
        //crearContactoFondo.setBackground(new Color(255, 102, 204));         // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoBtnMouseReleased

    private void crearContactoFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoFondoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoFondoMouseDragged

    private void crearContactoFondoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_crearContactoFondoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoFondoFocusGained

    private void crearContactoFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoFondoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoFondoMousePressed

    private void crearContactoFondoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoFondoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoFondoMouseReleased

    private void nombreRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreRegistrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreRegistrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crearContactoBtn;
    private javax.swing.JPanel crearContactoFondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nombreRegistrar1;
    // End of variables declaration//GEN-END:variables
}
