/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete.franquito;

/**
 *
 * @author LENOVO
 */
public class ContactoGui extends javax.swing.JFrame {

    /**
     * Creates new form ContactoGui
     */
    public ContactoGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        crearContactoFondo = new javax.swing.JPanel();
        crearContactoBtn = new javax.swing.JLabel();
        nombreRegistrar1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        correoRegistrar1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        nombreRegistrar2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        correoRegistrar2 = new javax.swing.JTextField();
        correoRegistrar3 = new javax.swing.JTextField();
        correoRegistrar4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(10, 10));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AGREGAR CONTACTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, 77));

        crearContactoFondo.setBackground(new java.awt.Color(255, 102, 204));
        crearContactoFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                crearContactoFondoMouseDragged(evt);
            }
        });
        crearContactoFondo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                crearContactoFondoFocusGained(evt);
            }
        });
        crearContactoFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearContactoFondoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                crearContactoFondoMouseReleased(evt);
            }
        });

        crearContactoBtn.setBackground(new java.awt.Color(255, 102, 204));
        crearContactoBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        crearContactoBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearContactoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearContactoBtn.setText("AGREGAR CONTACTO");
        crearContactoBtn.setToolTipText("");
        crearContactoBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                crearContactoBtnFocusGained(evt);
            }
        });
        crearContactoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearContactoBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearContactoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearContactoBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                crearContactoBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout crearContactoFondoLayout = new javax.swing.GroupLayout(crearContactoFondo);
        crearContactoFondo.setLayout(crearContactoFondoLayout);
        crearContactoFondoLayout.setHorizontalGroup(
            crearContactoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearContactoFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearContactoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        crearContactoFondoLayout.setVerticalGroup(
            crearContactoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearContactoFondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(crearContactoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(crearContactoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, -1));

        nombreRegistrar1.setBackground(new java.awt.Color(204, 204, 255));
        nombreRegistrar1.setForeground(new java.awt.Color(153, 153, 255));
        nombreRegistrar1.setText("Ingrese usuario");
        nombreRegistrar1.setBorder(null);
        nombreRegistrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombreRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreRegistrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(nombreRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 260, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 255));
        jLabel8.setText("DNI");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 30));

        correoRegistrar1.setBackground(new java.awt.Color(204, 204, 255));
        correoRegistrar1.setForeground(new java.awt.Color(153, 153, 255));
        correoRegistrar1.setText("Ingrese correo");
        correoRegistrar1.setToolTipText("");
        correoRegistrar1.setBorder(null);
        correoRegistrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        correoRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoRegistrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(correoRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 260, -1));

        jSeparator5.setBackground(new java.awt.Color(102, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(153, 102, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 260, 10));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 255));
        jLabel9.setText("NOMBRE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 30));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 255));
        jLabel10.setText("APELLIDO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 30));

        jSeparator6.setBackground(new java.awt.Color(102, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(153, 102, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 260, 10));

        jSeparator4.setBackground(new java.awt.Color(255, 204, 153));
        jSeparator4.setForeground(new java.awt.Color(153, 102, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 260, 10));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 255));
        jLabel11.setText("DIRECCION");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 30));

        jSeparator7.setBackground(new java.awt.Color(255, 204, 153));
        jSeparator7.setForeground(new java.awt.Color(153, 102, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 260, 10));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 255));
        jLabel12.setText("CORREO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 30));

        jSeparator8.setBackground(new java.awt.Color(102, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(153, 102, 255));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 260, 10));

        nombreRegistrar2.setBackground(new java.awt.Color(204, 204, 255));
        nombreRegistrar2.setForeground(new java.awt.Color(153, 153, 255));
        nombreRegistrar2.setText("Ingrese usuario");
        nombreRegistrar2.setBorder(null);
        nombreRegistrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombreRegistrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreRegistrar2ActionPerformed(evt);
            }
        });
        jPanel1.add(nombreRegistrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 260, -1));

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 255));
        jLabel13.setText("LOCALIDAD");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, 30));

        jSeparator9.setBackground(new java.awt.Color(102, 255, 255));
        jSeparator9.setForeground(new java.awt.Color(153, 102, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 260, 10));

        correoRegistrar2.setBackground(new java.awt.Color(204, 204, 255));
        correoRegistrar2.setForeground(new java.awt.Color(153, 153, 255));
        correoRegistrar2.setText("Ingrese correo");
        correoRegistrar2.setToolTipText("");
        correoRegistrar2.setBorder(null);
        correoRegistrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        correoRegistrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoRegistrar2ActionPerformed(evt);
            }
        });
        jPanel1.add(correoRegistrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 260, -1));

        correoRegistrar3.setBackground(new java.awt.Color(204, 204, 255));
        correoRegistrar3.setForeground(new java.awt.Color(153, 153, 255));
        correoRegistrar3.setText("Ingrese correo");
        correoRegistrar3.setToolTipText("");
        correoRegistrar3.setBorder(null);
        correoRegistrar3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        correoRegistrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoRegistrar3ActionPerformed(evt);
            }
        });
        jPanel1.add(correoRegistrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 260, -1));

        correoRegistrar4.setBackground(new java.awt.Color(204, 204, 255));
        correoRegistrar4.setForeground(new java.awt.Color(153, 153, 255));
        correoRegistrar4.setText("Ingrese correo");
        correoRegistrar4.setToolTipText("");
        correoRegistrar4.setBorder(null);
        correoRegistrar4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        correoRegistrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoRegistrar4ActionPerformed(evt);
            }
        });
        jPanel1.add(correoRegistrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearContactoBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_crearContactoBtnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoBtnFocusGained

    private void crearContactoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoBtnMouseClicked

    private void crearContactoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoBtnMouseExited

    private void crearContactoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoBtnMousePressed
       // crearContactoFondo.setBackground(new Color(255,153,204));  // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoBtnMousePressed

    private void crearContactoBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoBtnMouseReleased
       //crearContactoFondo.setBackground(new Color(255, 102, 204));         // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoBtnMouseReleased

    private void crearContactoFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoFondoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoFondoMouseDragged

    private void crearContactoFondoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_crearContactoFondoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoFondoFocusGained

    private void crearContactoFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoFondoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoFondoMousePressed

    private void crearContactoFondoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearContactoFondoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_crearContactoFondoMouseReleased

    private void nombreRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreRegistrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreRegistrar1ActionPerformed

    private void correoRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoRegistrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoRegistrar1ActionPerformed

    private void nombreRegistrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreRegistrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreRegistrar2ActionPerformed

    private void correoRegistrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoRegistrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoRegistrar2ActionPerformed

    private void correoRegistrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoRegistrar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoRegistrar3ActionPerformed

    private void correoRegistrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoRegistrar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoRegistrar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactoGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField correoRegistrar1;
    private javax.swing.JTextField correoRegistrar2;
    private javax.swing.JTextField correoRegistrar3;
    private javax.swing.JTextField correoRegistrar4;
    private javax.swing.JLabel crearContactoBtn;
    private javax.swing.JPanel crearContactoFondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField nombreRegistrar1;
    private javax.swing.JTextField nombreRegistrar2;
    // End of variables declaration//GEN-END:variables
}
